import { Player, RosterItem } from "types/hockeyCards";

export const players: Record<string, Player> = {
  mikael: {
    id: 8475798,
    fullName: "Mikael Granlund",
    link: "/api/v1/people/8475798",
    firstName: "Mikael",
    lastName: "Granlund",
    primaryNumber: "64",
    birthDate: "1992-02-26",
    currentAge: 29,
    birthCity: "Oulu",
    birthCountry: "FIN",
    nationality: "FIN",
    height: "5' 10\"",
    weight: 185,
    active: true,
    alternateCaptain: false,
    captain: false,
    rookie: false,
    shootsCatches: "L",
    rosterStatus: "Y",
    currentTeam: {
      id: 18,
      name: "Nashville Predators",
      link: "/api/v1/teams/18",
    },
    primaryPosition: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  pekka: {
    id: 8471469,
    fullName: "Pekka Rinne",
    link: "/api/v1/people/8471469",
    firstName: "Pekka",
    lastName: "Rinne",
    primaryNumber: "35",
    birthDate: "1982-11-03",
    currentAge: 38,
    birthCity: "Kempele",
    birthCountry: "FIN",
    nationality: "FIN",
    height: "6' 5\"",
    weight: 217,
    active: true,
    alternateCaptain: false,
    captain: false,
    rookie: false,
    shootsCatches: "L",
    rosterStatus: "Y",
    currentTeam: {
      id: 18,
      name: "Nashville Predators",
      link: "/api/v1/teams/18",
    },
    primaryPosition: {
      code: "G",
      name: "Goalie",
      type: "Goalie",
      abbreviation: "G",
    },
  },
  jani: {
    id: 8475825,
    fullName: "Jani Hakanpaa",
    link: "/api/v1/people/8475825",
    firstName: "Jani",
    lastName: "Hakanpaa",
    primaryNumber: "58",
    birthDate: "1992-03-31",
    currentAge: 29,
    birthCity: "Kirkkonummi",
    birthCountry: "FIN",
    nationality: "FIN",
    height: "6' 5\"",
    weight: 218,
    active: true,
    alternateCaptain: false,
    captain: false,
    rookie: false,
    shootsCatches: "R",
    rosterStatus: "Y",
    currentTeam: {
      id: 12,
      name: "Carolina Hurricanes",
      link: "/api/v1/teams/12",
    },
    primaryPosition: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  sebastian: {
    id: 8478427,
    fullName: "Sebastian Aho",
    link: "/api/v1/people/8478427",
    firstName: "Sebastian",
    lastName: "Aho",
    primaryNumber: "20",
    birthDate: "1997-07-26",
    currentAge: 23,
    birthCity: "Rauma",
    birthCountry: "FIN",
    nationality: "FIN",
    height: "6' 0\"",
    weight: 176,
    active: true,
    alternateCaptain: false,
    captain: false,
    rookie: false,
    shootsCatches: "L",
    rosterStatus: "Y",
    currentTeam: {
      id: 12,
      name: "Carolina Hurricanes",
      link: "/api/v1/teams/12",
    },
    primaryPosition: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
};

export const roster: RosterItem[] = [
  {
    person: {
      id: 8470755,
      fullName: "Brad Richardson",
      link: "/api/v1/people/8470755",
    },
    jerseyNumber: "15",
    position: {
      code: "R",
      name: "Right Wing",
      type: "Forward",
      abbreviation: "RW",
    },
  },
  {
    person: {
      id: 8474579,
      fullName: "Luca Sbisa",
      link: "/api/v1/people/8474579",
    },
    jerseyNumber: "55",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8474697,
      fullName: "Mark Borowiecki",
      link: "/api/v1/people/8474697",
    },
    jerseyNumber: "90",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8476887,
      fullName: "Filip Forsberg",
      link: "/api/v1/people/8476887",
    },
    jerseyNumber: "9",
    position: {
      code: "L",
      name: "Left Wing",
      type: "Forward",
      abbreviation: "LW",
    },
  },
  {
    person: {
      id: 8478851,
      fullName: "Alexandre Carrier",
      link: "/api/v1/people/8478851",
    },
    jerseyNumber: "45",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8479671,
      fullName: "Mathieu Olivier",
      link: "/api/v1/people/8479671",
    },
    jerseyNumber: "25",
    position: {
      code: "R",
      name: "Right Wing",
      type: "Forward",
      abbreviation: "RW",
    },
  },
  {
    person: {
      id: 8477343,
      fullName: "Tyler Lewington",
      link: "/api/v1/people/8477343",
    },
    jerseyNumber: "2",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8477446,
      fullName: "Michael McCarron",
      link: "/api/v1/people/8477446",
    },
    jerseyNumber: "47",
    position: {
      code: "R",
      name: "Right Wing",
      type: "Forward",
      abbreviation: "RW",
    },
  },
  {
    person: {
      id: 8479288,
      fullName: "Kasimir Kaskisuo",
      link: "/api/v1/people/8479288",
    },
    jerseyNumber: "73",
    position: {
      code: "G",
      name: "Goalie",
      type: "Goalie",
      abbreviation: "G",
    },
  },
  {
    person: {
      id: 8479514,
      fullName: "Rem Pitlick",
      link: "/api/v1/people/8479514",
    },
    jerseyNumber: "16",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8481577,
      fullName: "Philip Tomasino",
      link: "/api/v1/people/8481577",
    },
    jerseyNumber: "26",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8471469,
      fullName: "Pekka Rinne",
      link: "/api/v1/people/8471469",
    },
    jerseyNumber: "35",
    position: {
      code: "G",
      name: "Goalie",
      type: "Goalie",
      abbreviation: "G",
    },
  },
  {
    person: {
      id: 8474600,
      fullName: "Roman Josi",
      link: "/api/v1/people/8474600",
    },
    jerseyNumber: "59",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8475168,
      fullName: "Matt Duchene",
      link: "/api/v1/people/8475168",
    },
    jerseyNumber: "95",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8475176,
      fullName: "Ryan Ellis",
      link: "/api/v1/people/8475176",
    },
    jerseyNumber: "4",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8475218,
      fullName: "Mattias Ekholm",
      link: "/api/v1/people/8475218",
    },
    jerseyNumber: "14",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8475287,
      fullName: "Erik Haula",
      link: "/api/v1/people/8475287",
    },
    jerseyNumber: "56",
    position: {
      code: "L",
      name: "Left Wing",
      type: "Forward",
      abbreviation: "LW",
    },
  },
  {
    person: {
      id: 8475714,
      fullName: "Calle Jarnkrok",
      link: "/api/v1/people/8475714",
    },
    jerseyNumber: "19",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8475790,
      fullName: "Erik Gudbranson",
      link: "/api/v1/people/8475790",
    },
    jerseyNumber: "44",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8475793,
      fullName: "Ryan Johansen",
      link: "/api/v1/people/8475793",
    },
    jerseyNumber: "92",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8475798,
      fullName: "Mikael Granlund",
      link: "/api/v1/people/8475798",
    },
    jerseyNumber: "64",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8476393,
      fullName: "Nick Cousins",
      link: "/api/v1/people/8476393",
    },
    jerseyNumber: "21",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8476428,
      fullName: "Rocco Grimaldi",
      link: "/api/v1/people/8476428",
    },
    jerseyNumber: "23",
    position: {
      code: "R",
      name: "Right Wing",
      type: "Forward",
      abbreviation: "RW",
    },
  },
  {
    person: {
      id: 8476925,
      fullName: "Colton Sissons",
      link: "/api/v1/people/8476925",
    },
    jerseyNumber: "10",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8476988,
      fullName: "Matt Benning",
      link: "/api/v1/people/8476988",
    },
    jerseyNumber: "5",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8477424,
      fullName: "Juuse Saros",
      link: "/api/v1/people/8477424",
    },
    jerseyNumber: "74",
    position: {
      code: "G",
      name: "Goalie",
      type: "Goalie",
      abbreviation: "G",
    },
  },
  {
    person: {
      id: 8477433,
      fullName: "Ben Harpur",
      link: "/api/v1/people/8477433",
    },
    jerseyNumber: "17",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8478042,
      fullName: "Viktor Arvidsson",
      link: "/api/v1/people/8478042",
    },
    jerseyNumber: "33",
    position: {
      code: "R",
      name: "Right Wing",
      type: "Forward",
      abbreviation: "RW",
    },
  },
  {
    person: {
      id: 8478508,
      fullName: "Yakov Trenin",
      link: "/api/v1/people/8478508",
    },
    jerseyNumber: "13",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8479316,
      fullName: "Luke Kunin",
      link: "/api/v1/people/8479316",
    },
    jerseyNumber: "11",
    position: {
      code: "C",
      name: "Center",
      type: "Forward",
      abbreviation: "C",
    },
  },
  {
    person: {
      id: 8479371,
      fullName: "Dante Fabbro",
      link: "/api/v1/people/8479371",
    },
    jerseyNumber: "57",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8479602,
      fullName: "Jeremy Davies",
      link: "/api/v1/people/8479602",
    },
    jerseyNumber: "38",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
  {
    person: {
      id: 8479661,
      fullName: "Tanner Jeannot",
      link: "/api/v1/people/8479661",
    },
    jerseyNumber: "84",
    position: {
      code: "L",
      name: "Left Wing",
      type: "Forward",
      abbreviation: "LW",
    },
  },
  {
    person: {
      id: 8480009,
      fullName: "Eeli Tolvanen",
      link: "/api/v1/people/8480009",
    },
    jerseyNumber: "28",
    position: {
      code: "R",
      name: "Right Wing",
      type: "Forward",
      abbreviation: "RW",
    },
  },
  {
    person: {
      id: 8480063,
      fullName: "David Farrance",
      link: "/api/v1/people/8480063",
    },
    jerseyNumber: "22",
    position: {
      code: "D",
      name: "Defenseman",
      type: "Defenseman",
      abbreviation: "D",
    },
  },
];
